# Generated by Django 4.1.5 on 2023-01-31 08:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.FileField(upload_to='trials/')),
                ('Username', models.CharField(max_length=20)),
                ('path', models.CharField(blank=True, max_length=60, null=True)),
                ('Name', models.CharField(max_length=200)),
                ('Actions', models.CharField(max_length=400)),
                ('Module', models.CharField(max_length=400)),
                ('date_of_action', models.DateTimeField(auto_now_add=True)),
                ('operating_system', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=200)),
                ('user_agent', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'audittrials',
            },
        ),
        migrations.CreateModel(
            name='ErrorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=500)),
                ('Expected_error', models.CharField(max_length=500)),
                ('field_error', models.CharField(max_length=500)),
                ('trace_back', models.TextField(max_length=500)),
                ('line_number', models.IntegerField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('browser', models.CharField(max_length=500)),
                ('ip_address', models.CharField(max_length=500)),
                ('user_agent', models.TextField(max_length=500)),
                ('Avatar', models.FileField(blank=True, null=True, upload_to='errorlogs/')),
            ],
            options={
                'db_table': 'errorlogs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('avatar', models.FileField(upload_to='Avatars/')),
                ('is_admin', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('-username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
