# Generated by Django 4.1.5 on 2023-02-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='federal_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Customers.federal_state'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_state',
            field=models.BooleanField(default=False),
        ),
    ]
