# Generated by Django 4.1.5 on 2023-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_users_place_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_place_issue',
            field=models.BooleanField(default=False),
        ),
    ]
