# Generated by Django 4.1.5 on 2023-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_voucher',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
