# Generated by Django 4.1.5 on 2023-02-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_receipt_voucher_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
