# Generated by Django 4.1.5 on 2023-02-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Finance", "0002_account_types_alter_account_account_type"),
        ("Customers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="full_name",
        ),
        migrations.AddField(
            model_name="license",
            name="receipt_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="receipt_voucher",
                to="Finance.receipt_voucher",
            ),
        ),
        migrations.AlterModelTable(
            name="personal_id_type",
            table="personal_id_type",
        ),
    ]
