# Generated by Django 4.1.5 on 2023-02-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Finance', '0001_initial'),
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='receipt_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_voucher', to='Finance.receipt_voucher'),
        ),
    ]
