# Generated by Django 4.1.5 on 2023-03-08 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Customers", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"permissions": [("activate_customer", "Can Activate Customer")]},
        ),
    ]
