# Generated by Django 4.1.5 on 2023-02-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_license_receipt_voucher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personal_id_type',
            table='personal_id_type',
        ),
    ]
