# Generated by Django 4.1.5 on 2023-03-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('unblock_company', 'Can unblock company')]},
        ),
    ]
