# Generated by Django 4.1.5 on 2023-02-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_licensetype_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='document',
            field=models.FileField(blank=True, max_length=80, null=True, upload_to='comapany_document'),
        ),
    ]
