# Generated by Django 4.1.5 on 2023-03-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_placeissue_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'permissions': [('change_status', 'Can change license status')]},
        ),
    ]
