# Generated by Django 4.1.5 on 2023-02-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_placeissue_reg_user_alter_placeissue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='place_of_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Customers.placeissue'),
        ),
    ]
