# Generated by Django 4.1.5 on 2023-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo_bgr',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images'),
        ),
    ]
