# Generated by Django 4.1.5 on 2023-03-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_alter_license_place_of_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blood_group',
            name='modified_at',
        ),
    ]
