# Generated by Django 4.1.5 on 2023-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_customer_photo_bgr'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
