# Generated by Django 4.1.5 on 2023-03-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_company_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo_bgr',
        ),
    ]
