# Generated by Django 4.1.5 on 2023-03-04 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_remove_blood_group_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blood_group',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
