# Generated by Django 4.1.5 on 2023-03-05 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='cylinder',
            fields=[
                ('cylinder_id', models.AutoField(primary_key=True, serialize=False)),
                ('cylinder_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cylinder',
            },
        ),
        migrations.CreateModel(
            name='model_brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_brand',
            },
        ),
        migrations.CreateModel(
            name='plate',
            fields=[
                ('plate_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_code', models.CharField(max_length=100)),
                ('plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Customers.federal_state')),
            ],
            options={
                'db_table': 'plate',
            },
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('hp', models.CharField(blank=True, max_length=100, null=True)),
                ('pessenger_seat', models.TextField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True)),
                ('enginer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rv_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.color')),
                ('cylinder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.cylinder')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Customers.countries')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Customers.customer')),
                ('plate_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.plate')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.model_brand')),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='transfare_vehicles',
            fields=[
                ('transfare_id', models.AutoField(primary_key=True, serialize=False)),
                ('rv_number', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='transfare_document')),
                ('description', models.TextField(blank=True, null=True)),
                ('transfare_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_for_new_owner', to='Customers.customer')),
                ('old_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_for_old_owner', to='Customers.customer')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='plate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.type'),
        ),
        migrations.CreateModel(
            name='code_plate',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'code_plate',
            },
        ),
    ]
