# Generated by Django 4.1.5 on 2023-02-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.type'),
        ),
    ]
