# Generated by Django 4.1.5 on 2023-03-16 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vehicles', '0003_alter_plate_plate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_elements',
            fields=[
                ('el_id', models.AutoField(primary_key=True, serialize=False)),
                ('el_name', models.TextField()),
                ('result', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='test_category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_meter', models.BigIntegerField()),
                ('expired_date', models.DateField()),
                ('issue_date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('test_cat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.test_category')),
                ('tested_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.vehicle')),
            ],
        ),
    ]
