# Generated by Django 4.1.5 on 2023-02-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0003_plate_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transfare_vehicles',
            table='vehicles_transfare_vehicles',
        ),
    ]
