# Generated by Django 4.1.5 on 2023-02-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0004_alter_transfare_vehicles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transfare_vehicles',
            table=None,
        ),
    ]
