# Generated by Django 4.1.5 on 2023-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0005_alter_transfare_vehicles_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='plate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
