# Generated by Django 4.1.5 on 2023-02-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0006_alter_plate_plate_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.plate'),
        ),
    ]
