# Generated by Django 4.1.5 on 2023-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0007_remove_test_result_remove_test_tested_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
