# Generated by Django 4.1.5 on 2023-02-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0007_remove_plate_vehicle_vehicle_plate_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
