# Generated by Django 4.1.5 on 2023-03-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0008_test_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='plate_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Vehicles.code_plate', unique=True),
        ),
    ]
