# Generated by Django 4.1.5 on 2023-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0009_alter_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='pessenger_seat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
