# Generated by Django 4.1.5 on 2023-03-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0010_alter_vehicle_pessenger_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
