# Generated by Django 4.1.5 on 2023-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0010_alter_code_plate_code_name_alter_plate_plate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_plate',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
